name: Deploy TaskFlow

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # ==========================================================
      # 1. Checkout source code
      # ==========================================================
      - name: Checkout repository
        uses: actions/checkout@v6


      # ==========================================================
      # 2. Login to GitHub Container Registry
      # ==========================================================
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # ==========================================================
      # 3. Build and push Docker image
      # ==========================================================
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ghcr.io/pavan200212345/taskflow:latest


      # ==========================================================
      # 4. Deploy image to Server 1
      # ==========================================================
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |

            set -e

            echo "======================================"
            echo " Deploying TaskFlow"
            echo "======================================"

            IMAGE="ghcr.io/pavan200212345/taskflow:latest"
            CONTAINER="taskflow-nginx"

            echo ""
            echo "[1/5] Checking Docker..."

            if ! command -v docker >/dev/null 2>&1; then
              echo "ERROR: Docker is not installed."
              exit 1
            fi

            echo ""
            echo "[2/5] Logging into GHCR..."

            echo "${{ secrets.GHCR_TOKEN }}" | \
              docker login ghcr.io \
              -u "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin

            echo ""
            echo "[3/5] Pulling latest image..."

            docker pull "$IMAGE"

            echo ""
            echo "[4/5] Replacing old container..."

            docker rm -f "$CONTAINER" 2>/dev/null || true

            docker run -d \
              --name "$CONTAINER" \
              --restart unless-stopped \
              -p 80:80 \
              "$IMAGE"

            echo ""
            echo "[5/5] Checking deployment..."

            sleep 5

            docker ps

            echo ""
            echo "Deployment completed successfully."